# Generated by Django 4.1.5 on 2023-09-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Golfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('player_cost', models.IntegerField(default=0)),
                ('started_round', models.BooleanField(default=False)),
                ('cut', models.BooleanField(default=False)),
                ('point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_budget', models.IntegerField()),
                ('team_size', models.IntegerField()),
                ('user_password', models.CharField(max_length=30)),
                ('course_par', models.IntegerField(default=0)),
                ('tourn_pga_link', models.CharField(default='a', max_length=100)),
                ('curr_stage', models.CharField(choices=[('r_1', 'Round 1'), ('r_3', 'Round 3'), ('init_tourn', 'Initialize Players'), ('r_2', 'Round 2'), ('pre', 'Pre Tournament'), ('r_4', 'Round 4')], default='pre', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30, unique=True)),
                ('team_owner', models.CharField(max_length=30)),
                ('team_cost', models.IntegerField(default=0)),
                ('team_points', models.IntegerField(default=0)),
                ('password_used', models.CharField(default='test', max_length=30)),
                ('cut', models.BooleanField(default=False)),
                ('team_golfers', models.ManyToManyField(to='golf_app.golfer')),
            ],
        ),
    ]
