# Generated by Django 4.1.5 on 2023-02-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0002_golfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('team_owner', models.CharField(max_length=30, unique=True)),
                ('team_cost', models.IntegerField()),
                ('team_points', models.IntegerField()),
                ('team_golfers', models.ManyToManyField(to='golf_app.golfer')),
            ],
        ),
    ]
