# Generated by Django 4.1.5 on 2023-03-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0003_alter_blogpost_timestamp_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_budget', models.IntegerField()),
                ('team_size', models.IntegerField()),
                ('user_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='team_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_points',
            field=models.IntegerField(default=0),
        ),
    ]
