# Generated by Django 4.1.5 on 2023-03-21 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0005_team_creation_time_team_password_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='golfer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='golfer',
            name='last_name',
        ),
    ]
