# Generated by Django 4.1.5 on 2023-03-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0006_rename_first_name_golfer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfer',
            name='cut',
            field=models.BooleanField(default=False),
        ),
    ]
