# Generated by Django 4.1.5 on 2023-03-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0007_golfer_cut'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonsettings',
            name='course_par',
            field=models.IntegerField(default=0),
        ),
    ]
