# Generated by Django 4.1.5 on 2023-03-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0008_seasonsettings_course_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonsettings',
            name='tourn_pga_link',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
