# Generated by Django 4.1.5 on 2023-03-27 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0009_seasonsettings_tourn_pga_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfer',
            name='player_id',
        ),
    ]
