# Generated by Django 4.1.5 on 2023-03-28 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0011_alter_team_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='creation_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 28, 23, 8, 3, 713999, tzinfo=datetime.timezone.utc)),
        ),
    ]
