# Generated by Django 4.1.5 on 2023-03-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0013_remove_team_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_owner',
            field=models.CharField(max_length=30),
        ),
    ]
