# Generated by Django 4.1.5 on 2023-03-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0014_alter_team_team_name_alter_team_team_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfer',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
