# Generated by Django 4.1.5 on 2023-03-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0015_alter_golfer_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonsettings',
            name='curr_stage',
            field=models.CharField(choices=[('r_1', 'Round 1'), ('pre', 'Pre Tournament')], default='pre', max_length=30),
        ),
    ]
