# Generated by Django 4.1.5 on 2023-03-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0016_seasonsettings_curr_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfer',
            name='r1_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfer',
            name='r2_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfer',
            name='r3_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfer',
            name='r4_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seasonsettings',
            name='curr_stage',
            field=models.CharField(choices=[('r_1', 'Round 1'), ('r_3', 'Round 3'), ('pre', 'Pre Tournament'), ('r_4', 'Round 4'), ('r_2', 'Round 2')], default='pre', max_length=30),
        ),
    ]
