# Generated by Django 4.1.5 on 2023-03-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0017_golfer_r1_points_golfer_r2_points_golfer_r3_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='r_1_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='r_2_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='r_3_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='r_4_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seasonsettings',
            name='curr_stage',
            field=models.CharField(choices=[('r_3', 'Round 3'), ('r_4', 'Round 4'), ('r_1', 'Round 1'), ('pre', 'Pre Tournament'), ('r_2', 'Round 2')], default='pre', max_length=30),
        ),
    ]
