# Generated by Django 4.1.5 on 2023-03-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0018_team_r_1_points_team_r_2_points_team_r_3_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='cut',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seasonsettings',
            name='curr_stage',
            field=models.CharField(choices=[('r_4', 'Round 4'), ('r_3', 'Round 3'), ('r_1', 'Round 1'), ('pre', 'Pre Tournament'), ('r_2', 'Round 2')], default='pre', max_length=30),
        ),
    ]
