# Generated by Django 4.1.5 on 2023-03-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0019_team_cut_alter_seasonsettings_curr_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonsettings',
            name='curr_stage',
            field=models.CharField(choices=[('r_4', 'Round 4'), ('init_tourn', 'Initialize Players'), ('r_3', 'Round 3'), ('pre', 'Pre Tournament'), ('r_2', 'Round 2'), ('r_1', 'Round 1')], default='pre', max_length=30),
        ),
    ]
