# Generated by Django 4.1.5 on 2023-03-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0020_alter_seasonsettings_curr_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfer',
            name='started_round',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seasonsettings',
            name='curr_stage',
            field=models.CharField(choices=[('init_tourn', 'Initialize Players'), ('r_1', 'Round 1'), ('r_4', 'Round 4'), ('r_3', 'Round 3'), ('r_2', 'Round 2'), ('pre', 'Pre Tournament')], default='pre', max_length=30),
        ),
    ]
