# Generated by Django 4.1.5 on 2023-03-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0021_golfer_started_round_alter_seasonsettings_curr_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfer',
            name='started_round',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seasonsettings',
            name='curr_stage',
            field=models.CharField(choices=[('pre', 'Pre Tournament'), ('init_tourn', 'Initialize Players'), ('r_4', 'Round 4'), ('r_3', 'Round 3'), ('r_2', 'Round 2'), ('r_1', 'Round 1')], default='pre', max_length=30),
        ),
    ]
