# Generated by Django 4.1.5 on 2023-03-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0022_alter_golfer_started_round_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonsettings',
            name='curr_stage',
            field=models.CharField(choices=[('init_tourn', 'Initialize Players'), ('r_1', 'Round 1'), ('r_3', 'Round 3'), ('r_4', 'Round 4'), ('pre', 'Pre Tournament'), ('r_2', 'Round 2')], default='pre', max_length=30),
        ),
    ]
