# Generated by Django 4.1.5 on 2023-03-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0023_alter_seasonsettings_curr_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfer',
            name='r1_points',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='golfer',
            name='r2_points',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='golfer',
            name='r3_points',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='golfer',
            name='r4_points',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='seasonsettings',
            name='curr_stage',
            field=models.CharField(choices=[('pre', 'Pre Tournament'), ('r_3', 'Round 3'), ('r_2', 'Round 2'), ('r_4', 'Round 4'), ('init_tourn', 'Initialize Players'), ('r_1', 'Round 1')], default='pre', max_length=30),
        ),
    ]
