# Generated by Django 4.1.5 on 2023-03-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0024_alter_golfer_r1_points_alter_golfer_r2_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonsettings',
            name='curr_stage',
            field=models.CharField(choices=[('pre', 'Pre Tournament'), ('r_4', 'Round 4'), ('r_3', 'Round 3'), ('r_2', 'Round 2'), ('init_tourn', 'Initialize Players'), ('r_1', 'Round 1')], default='pre', max_length=30),
        ),
    ]
