# Generated by Django 4.1.5 on 2023-03-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0028_alter_seasonsettings_curr_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfer',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='golfer',
            name='player_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seasonsettings',
            name='curr_stage',
            field=models.CharField(choices=[('init_tourn', 'Initialize Players'), ('pre', 'Pre Tournament'), ('r_1', 'Round 1'), ('r_2', 'Round 2'), ('r_4', 'Round 4'), ('r_3', 'Round 3')], default='pre', max_length=30),
        ),
    ]
