# Generated by Django 4.1.5 on 2023-04-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0029_alter_golfer_name_alter_golfer_player_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfer',
            name='r1_points',
        ),
        migrations.RemoveField(
            model_name='golfer',
            name='r2_points',
        ),
        migrations.RemoveField(
            model_name='golfer',
            name='r3_points',
        ),
        migrations.RemoveField(
            model_name='golfer',
            name='r4_points',
        ),
        migrations.RemoveField(
            model_name='team',
            name='r_1_points',
        ),
        migrations.RemoveField(
            model_name='team',
            name='r_2_points',
        ),
        migrations.RemoveField(
            model_name='team',
            name='r_3_points',
        ),
        migrations.RemoveField(
            model_name='team',
            name='r_4_points',
        ),
        migrations.AlterField(
            model_name='seasonsettings',
            name='curr_stage',
            field=models.CharField(choices=[('init_tourn', 'Initialize Players'), ('r_4', 'Round 4'), ('r_2', 'Round 2'), ('pre', 'Pre Tournament'), ('r_1', 'Round 1'), ('r_3', 'Round 3')], default='pre', max_length=30),
        ),
    ]
